- Infrastructure:
    - Dashboard:
        icon: homepage
        href: http://dash.lan
        description: Homepage dashboard
    - Portainer:
        icon: portainer
        href: http://portainer.lan
        description: Container management
    - Glances:
        icon: glances
        href: http://glances.lan
        description: Host metrics endpoint

- Media:
    - Kyoo:
        icon: https://github.com/zoriya/Kyoo/blob/master/icons/icon-256x256.png?raw=true
        href: http://kyoo.lan
        description: Media server frontend

- Downloads:
    - qBittorrent:
        icon: qbittorrent
        href: http://qbit.lan
        description: Torrent client

- Arr:
    - Prowlarr:
        icon: prowlarr
        href: http://prowlarr.lan
        description: Indexer manager
    - Sonarr:
        icon: sonarr
        href: http://sonarr.lan
        description: TV automation
    - Radarr:
        icon: radarr
        href: http://radarr.lan
        description: Movie automation
    - Bazarr:
        icon: bazarr
        href: http://bazarr.lan
        description: Subtitle automation
